<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-01-15T10:32:13 BRT" name="Default suite" finished-at="2021-01-15T10:32:14 BRT" duration-ms="316">
    <groups>
    </groups>
    <test started-at="2021-01-15T10:32:13 BRT" name="Default test" finished-at="2021-01-15T10:32:14 BRT" duration-ms="316">
      <class name="com.publica.grupo2sprint3.model.dao.RoleDAOTest">
        <test-method signature="updateByIdentifierTest()[pri:0, instance:com.publica.grupo2sprint3.model.dao.RoleDAOTest@4a070cf0]" started-at="2021-01-15T10:32:13 BRT" name="updateByIdentifierTest" finished-at="2021-01-15T10:32:14 BRT" duration-ms="286" status="FAIL">
          <exception class="java.lang.IllegalStateException">
            <message>
              <![CDATA[Transaction already active]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalStateException: Transaction already active
at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:74)
at org.hibernate.internal.AbstractSharedSessionContract.beginTransaction(AbstractSharedSessionContract.java:471)
at com.publica.grupo2sprint3.model.dao.RoleDAO.findByIdentifier(RoleDAO.java:94)
at com.publica.grupo2sprint3.model.dao.RoleDAOTest.updateByIdentifierTest(RoleDAOTest.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalStateException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateByIdentifierTest -->
        <test-method is-config="true" signature="clear()[pri:0, instance:com.publica.grupo2sprint3.model.dao.RoleDAOTest@4a070cf0]" started-at="2021-01-15T10:32:14 BRT" name="clear" finished-at="2021-01-15T10:32:14 BRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clear -->
      </class> <!-- com.publica.grupo2sprint3.model.dao.RoleDAOTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
